import { StyleSheet } from 'react-native';

export const fonts = { body: 'InstrumentSans', heading: 'InstrumentSerif' };
const ink = '#1E241C';
const muted = '#62695B';
const green = '#2F5D3A';
const border = '#E0DECF';
const paper = '#FBFAF4';
const body = { fontFamily: fonts.body, color: ink };

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: paper },
  modalBackdrop: { backgroundColor: '#14251CB8' },
  keyboardToolbar: { flexDirection: 'row', justifyContent: 'flex-end', paddingHorizontal: 12, backgroundColor: paper, borderTopWidth: 1, borderColor: border },
  fill: { flex: 1, minHeight: 0 },
  // A content-sized ScrollView may override grow to 0. Native Yoga would
  // still derive a zero basis from flex: 1, even with flexBasis: 'auto'.
  formScroll: { flexGrow: 1, flexShrink: 1, minHeight: 0 },
  flexible: { flex: 1, minWidth: 0 },
  fontLoading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: paper },
  loginScroll: { flexGrow: 1, justifyContent: 'center', padding: 24 },
  login: { width: '100%', maxWidth: 440, alignSelf: 'center', gap: 28 },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  brandMark: { width: 34, height: 34, borderRadius: 11, backgroundColor: green, alignItems: 'center', justifyContent: 'center' },
  brandInitial: { fontFamily: fonts.heading, color: '#FFFFFF', fontSize: 25, lineHeight: 30 },
  brandName: { ...body, fontSize: 21, fontWeight: '600', letterSpacing: -0.5 },
  brandLink: { minHeight: 44, justifyContent: 'center', borderRadius: 10 },
  botMark: { width: 20, height: 20, borderRadius: 6 },
  botInitial: { fontSize: 15, lineHeight: 19 },
  title: { fontFamily: fonts.heading, color: ink, fontSize: 36, lineHeight: 40 },
  subtitle: { ...body, color: muted, fontSize: 15, lineHeight: 23 },
  eyebrow: { ...body, color: muted, fontSize: 10, fontWeight: '600', letterSpacing: 1.2, textTransform: 'uppercase' },
  card: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: border, borderRadius: 18, padding: 24, gap: 18 },
  field: { gap: 8 },
  label: { ...body, fontSize: 13, fontWeight: '600' },
  input: { ...body, borderWidth: 1, borderColor: '#B3B7A8', borderRadius: 10, minHeight: 48, paddingHorizontal: 14, paddingVertical: 12, backgroundColor: '#FFFFFF', fontSize: 16 },
  inputMultiline: { minHeight: 110, textAlignVertical: 'top' },
  button: { backgroundColor: green, borderWidth: 1, borderColor: green, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 10, minHeight: 44, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center' },
  buttonText: { ...body, fontSize: 13, fontWeight: '600', color: '#FFFFFF' },
  buttonSecondary: { backgroundColor: '#FFFFFF', borderColor: border },
  buttonSecondaryText: { color: green },
  buttonGhost: { backgroundColor: 'transparent', borderColor: 'transparent', paddingHorizontal: 10 },
  buttonChip: { borderRadius: 24, paddingHorizontal: 13 },
  chipText: { fontSize: 12, fontWeight: '500', color: '#4B5246' },
  buttonIcon: { width: 44, paddingHorizontal: 0 },
  buttonSelected: { backgroundColor: '#E7EEE0', borderColor: '#D5DECC' },
  disabled: { opacity: 0.5 },
  pressed: { opacity: 0.75 },
  focus: { outlineColor: green, outlineOffset: 2, outlineStyle: 'solid', outlineWidth: 2 },
  error: { ...body, color: '#982D23', fontSize: 14, lineHeight: 21 },
  success: { ...body, color: green, fontSize: 14, lineHeight: 21 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  inline: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  app: { flex: 1, minHeight: 0, width: '100%', flexDirection: 'row' },
  sidebar: { width: 264, borderRightWidth: 1, borderColor: border, backgroundColor: '#F4F3EA', paddingHorizontal: 18, paddingVertical: 22, gap: 28 },
  sidebarNav: { gap: 6 },
  historySection: { flex: 1, minHeight: 0, gap: 12 },
  sidebarBottom: { flexDirection: 'row', alignItems: 'center', gap: 4, borderTopWidth: 1, borderColor: border, paddingTop: 16 },
  profileLink: { flex: 1, minWidth: 0, minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 9, borderRadius: 10 },
  avatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#DCE5D5', alignItems: 'center', justifyContent: 'center' },
  avatarText: { ...body, color: green, fontSize: 11, fontWeight: '700' },
  small: { ...body, color: muted, fontSize: 12, lineHeight: 18 },
  main: { flex: 1, minWidth: 0, minHeight: 0, backgroundColor: paper },
  mobileHeader: { paddingHorizontal: 16, paddingTop: 4, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  topBar: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 12, gap: 8, borderBottomWidth: 1, borderColor: border },
  topBarWide: { paddingHorizontal: 32, paddingTop: 22, paddingBottom: 18 },
  topBarTyping: { paddingVertical: 6 },
  headingTyping: { fontSize: 21, lineHeight: 26 },
  dayHeading: { gap: 5, flexShrink: 1 },
  heading: { fontFamily: fonts.heading, color: ink, fontSize: 28, lineHeight: 33 },
  headingWide: { fontSize: 36, lineHeight: 40 },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8 },
  dateInput: { ...body, borderWidth: 1, borderColor: '#B3B7A8', borderRadius: 10, padding: 10, minHeight: 44, width: 144, fontSize: 16, backgroundColor: '#FFFFFF' },
  messages: { flexGrow: 1, padding: 16, gap: 20, width: '100%', maxWidth: 844, alignSelf: 'center' },
  messagesWide: { paddingHorizontal: 32, paddingTop: 24 },
  divider: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  dividerLine: { flex: 1, height: 1, backgroundColor: border },
  empty: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12, paddingVertical: 24, alignSelf: 'center', maxWidth: 440 },
  emptyTitle: { textAlign: 'center', fontSize: 30, lineHeight: 34 },
  emptyText: { textAlign: 'center' },
  message: { alignSelf: 'flex-end', maxWidth: '94%', borderWidth: 1, borderColor: '#D5E0C9', borderRadius: 16, paddingHorizontal: 16, paddingVertical: 13, gap: 8, backgroundColor: '#E7EEE0' },
  messageWide: { maxWidth: '78%' },
  assistantMessage: { alignSelf: 'flex-start', backgroundColor: '#FFFFFF', borderColor: border },
  assistantLabel: { ...body, color: green, fontSize: 12, fontWeight: '600' },
  messageText: { ...body, fontSize: 15, lineHeight: 23 },
  messageTime: { ...body, color: muted, fontSize: 11, lineHeight: 15 },
  composerFooter: { flexGrow: 0, flexShrink: 1, flexBasis: 'auto', maxHeight: '100%', borderTopWidth: 1, borderColor: border, backgroundColor: paper },
  composerArea: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 12, gap: 8, width: '100%', maxWidth: 844, alignSelf: 'center' },
  composerWide: { paddingHorizontal: 32, paddingBottom: 20 },
  composerAreaTyping: { paddingTop: 6, paddingBottom: 6, gap: 4 },
  suggestions: { gap: 8, padding: 2 },
  composer: { padding: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: border, borderRadius: 16, gap: 8 },
  composerFocused: { borderColor: '#6F8D69' },
  composerInput: { ...body, fontSize: 16, lineHeight: 23, minHeight: 48, maxHeight: 120, textAlignVertical: 'top', padding: 4, borderRadius: 4 },
  composerInputTyping: { maxHeight: 80 },
  composerBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  composerHint: { ...body, color: muted, fontSize: 11, flexShrink: 1, lineHeight: 16 },
  historyList: { gap: 6, paddingBottom: 12 },
  historyItem: { padding: 12, borderWidth: 1, borderColor: 'transparent', borderRadius: 12, gap: 7 },
  historySelected: { backgroundColor: '#FFFFFF', borderColor: '#D5DECC' },
  historyDate: { ...body, fontSize: 13, fontWeight: '600', flexShrink: 1 },
  historyCount: { ...body, color: green, backgroundColor: '#E7EEE4', borderRadius: 8, paddingHorizontal: 7, paddingVertical: 3, fontSize: 11, fontWeight: '500' },
  pageScroll: { padding: 24, gap: 20, width: '100%', maxWidth: 680, alignSelf: 'center' },
  analysisNotice: { alignSelf: 'flex-start', padding: 14, borderRadius: 14, backgroundColor: '#EDEFE5', gap: 8 },
  photoStrip: { flexDirection: 'row', gap: 10, paddingVertical: 4 },
  photoItem: { maxWidth: 180, gap: 8 },
  photoThumbnail: { width: 128, height: 104, borderRadius: 12, backgroundColor: '#E6E4D8' },
  photoDraft: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  photoDraftPreview: { width: 76, height: 60, borderRadius: 10, backgroundColor: '#E6E4D8' },
  photoModal: { flex: 1, padding: 24, paddingTop: 60, gap: 16, backgroundColor: '#14251CF2' },
  photoFull: { flex: 1, width: '100%' },
});
