import { StyleSheet } from 'react-native';
import { fonts } from './app';

export const styles = StyleSheet.create({
  card: { backgroundColor: '#FFFFFF', borderColor: '#E0DECF', borderWidth: 1, borderRadius: 18 },
  overview: { flexDirection: 'row', alignItems: 'center', gap: 32, paddingHorizontal: 24, paddingVertical: 20 },
  overviewCompact: { gap: 16, paddingHorizontal: 16, paddingVertical: 14 },
  targetsCompact: { flexDirection: 'column', alignItems: 'stretch', gap: 14 },
  calories: { minWidth: 150, gap: 3 },
  caloriesCompact: { minWidth: 86 },
  caloriesWithTargets: { maxWidth: 220, flexShrink: 1 },
  caloriesTargetCompact: { maxWidth: '100%' },
  eyebrow: { fontFamily: fonts.body, fontSize: 10, fontWeight: '600', letterSpacing: 1.1, textTransform: 'uppercase', color: '#62695B' },
  calorieValue: { fontFamily: fonts.heading, fontSize: 48, lineHeight: 51, color: '#2F5D3A' },
  calorieValueCompact: { fontSize: 42, lineHeight: 44 },
  caption: { fontFamily: fonts.body, fontSize: 11, lineHeight: 16, color: '#62695B' },
  macros: { flex: 1, minWidth: 0 },
  macrosTargetCompact: { flexGrow: 0, flexShrink: 0, flexBasis: 'auto' },
  macroSection: { gap: 6, paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: '#EFEEE3' },
  macroRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 4 },
  lastMacroRow: { borderBottomWidth: 0 },
  progress: { gap: 5, marginTop: 5 },
  progressCaption: { fontFamily: fonts.body, fontSize: 11, lineHeight: 16, color: '#62695B' },
  targetAction: { paddingHorizontal: 24, paddingBottom: 12, gap: 4, alignItems: 'flex-start' },
  targetActionCompact: { paddingHorizontal: 16 },
  macroLabel: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  dot: { width: 6, height: 6, borderRadius: 3 },
  proteinDot: { backgroundColor: '#3D6A49' },
  carbsDot: { backgroundColor: '#AD9158' },
  fatDot: { backgroundColor: '#B4765E' },
  label: { fontFamily: fonts.body, fontSize: 12, lineHeight: 16, color: '#414B3C' },
  macroValue: { fontFamily: fonts.body, fontSize: 13, lineHeight: 16, fontWeight: '600', color: '#253222' },
  activity: { paddingHorizontal: 24, paddingVertical: 12, gap: 4, borderTopWidth: 1, borderTopColor: '#EFEEE3', backgroundColor: '#FCFBF5' },
  activityCompact: { paddingHorizontal: 16, paddingVertical: 10 },
  activityHeading: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  activityMark: { width: 24, height: 24, borderRadius: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E7EEE4' },
  activityArrow: { fontFamily: fonts.body, fontSize: 16, lineHeight: 20, color: '#2F5D3A' },
  activityText: { fontFamily: fonts.body, flex: 1, fontSize: 12, lineHeight: 18, color: '#62695B' },
  activityLabel: { fontWeight: '600', color: '#253222' },
  entries: { paddingHorizontal: 24, borderTopWidth: 1, borderTopColor: '#EFEEE3' },
  entriesCompact: { paddingHorizontal: 16 },
  toggle: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8, paddingVertical: 8, borderRadius: 7 },
  toggleLabel: { fontFamily: fonts.body, fontSize: 13, lineHeight: 20, fontWeight: '600', color: '#2F5D3A' },
  toggleEnd: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  estimateBadge: { fontFamily: fonts.body, fontSize: 11, lineHeight: 16, fontWeight: '500', backgroundColor: '#F6EED8', color: '#765919', borderRadius: 99, paddingHorizontal: 8, paddingVertical: 3, overflow: 'hidden' },
  chevron: { fontFamily: fonts.body, fontSize: 19, lineHeight: 22, color: '#62695B' },
  pressed: { opacity: 0.7 },
  focus: { outlineColor: '#2F5D3A', outlineWidth: 2, outlineStyle: 'solid', outlineOffset: 2 },
  entryList: { gap: 10, paddingBottom: 16 },
  entry: { gap: 7, padding: 14, borderWidth: 1, borderColor: '#EDECE0', borderRadius: 12 },
  entryHeading: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 7 },
  entryTitle: { fontFamily: fonts.body, fontSize: 14, lineHeight: 20, fontWeight: '600', color: '#253222', flexGrow: 1, flexShrink: 1 },
  sourceBadge: { fontFamily: fonts.body, fontSize: 11, lineHeight: 16, fontWeight: '500', backgroundColor: '#E7EEE4', color: '#2F5D3A', borderRadius: 99, paddingHorizontal: 8, paddingVertical: 3, overflow: 'hidden' },
  detail: { fontFamily: fonts.body, fontSize: 12, lineHeight: 19, color: '#62695B' },
  correctAction: { alignSelf: 'flex-start', marginTop: 2 },
});
