import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F5F6F0' },
  scroll: { flexGrow: 1, alignItems: 'center', paddingHorizontal: 24, paddingVertical: 32 },
  page: { width: '100%', maxWidth: 720, gap: 32 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  brandMark: { width: 44, height: 44, borderRadius: 15, backgroundColor: '#294B36', alignItems: 'center', justifyContent: 'center' },
  brandInitial: { color: '#FFFFFF', fontSize: 28, fontWeight: '700' },
  brandName: { color: '#25382B', fontSize: 28, fontWeight: '700', letterSpacing: -1 },
  badge: { color: '#596359', fontSize: 13 },
  intro: { paddingTop: 36, gap: 18 },
  eyebrow: { color: '#526A54', fontSize: 12, fontWeight: '700', letterSpacing: 2 },
  title: { color: '#25382B', fontSize: 40, lineHeight: 46, fontWeight: '600', letterSpacing: -1.5 },
  description: { color: '#596359', fontSize: 18, lineHeight: 28, maxWidth: 560 },
  card: { padding: 28, gap: 16, backgroundColor: '#FFFFFF', borderRadius: 24, borderWidth: 1, borderColor: '#E1E6DC' },
  cardEyebrow: { color: '#66715F', fontSize: 11, fontWeight: '700', letterSpacing: 1.5 },
  cardTitle: { color: '#25382B', fontSize: 24, lineHeight: 32, fontWeight: '600' },
  cardDescription: { color: '#596359', fontSize: 16, lineHeight: 25 },
  topics: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  topic: { backgroundColor: '#EEF2E9', paddingVertical: 8, paddingHorizontal: 14, borderRadius: 20 },
  topicLabel: { color: '#425B40', fontSize: 13, fontWeight: '500' },
  notice: { paddingHorizontal: 4, gap: 8 },
  noticeTitle: { color: '#3E503E', fontSize: 15, fontWeight: '600' },
  noticeDescription: { color: '#596359', fontSize: 14, lineHeight: 22 },
  connection: { borderTopWidth: 1, borderTopColor: '#DDE3D7', paddingTop: 16, gap: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap' },
  connectionLabel: { color: '#596359', fontSize: 13 },
  retry: { paddingHorizontal: 12, paddingVertical: 12, minHeight: 44, borderWidth: 2, borderColor: 'transparent', borderRadius: 8 },
  retryFocused: { borderColor: '#294B36' },
  retryDisabled: { opacity: 0.5 },
  retryLabel: { color: '#294B36', fontSize: 13, fontWeight: '600' },
});
